/**
 * Shared icon map for Features section.
 * Used by both FeaturesSection (storefront render) and FeaturesEditDialog (admin editor).
 */

import {
    Clock,
    Shield,
    Lock,
    Star,
    Truck,
    Leaf,
    Heart,
    Zap,
    Award,
    CheckCircle,
    ThumbsUp,
    Gift,
    Sparkles,
    Globe,
    Users,
    Phone,
    MapPin,
    Package,
    BadgeCheck,
    Gem,
    Flame,
    Eye,
    Sun,
    Moon,
    Droplets,
    Wind,
    Timer,
    Headphones,
    ShieldCheck,
    Wallet,
    type LucideIcon,
} from 'lucide-react';

export const FEATURES_ICON_MAP: Record<string, LucideIcon> = {
    clock: Clock,
    shield: Shield,
    lock: Lock,
    star: Star,
    truck: Truck,
    leaf: Leaf,
    heart: Heart,
    zap: Zap,
    award: Award,
    'check-circle': CheckCircle,
    'thumbs-up': ThumbsUp,
    gift: Gift,
    sparkles: Sparkles,
    globe: Globe,
    users: Users,
    phone: Phone,
    'map-pin': MapPin,
    package: Package,
    'badge-check': BadgeCheck,
    gem: Gem,
    flame: Flame,
    eye: Eye,
    sun: Sun,
    moon: Moon,
    droplets: Droplets,
    wind: Wind,
    timer: Timer,
    headphones: Headphones,
    'shield-check': ShieldCheck,
    wallet: Wallet,
};

export type FeatureIconKey = keyof typeof FEATURES_ICON_MAP;
