/**
 * Send a purchase order notification email to the supplier via Resend.
 * Returns true if the email was sent, false if skipped (no provider or no email).
 */

interface SupplierEmailData {
  supplierEmail: string;
  supplierName: string;
  poNumber: string;
  businessName: string;
  items: Array<{
    product_name: string;
    quantity_lbs: number;
    price_per_lb: number;
    subtotal: number;
  }>;
  totalAmount: number;
  deliveryDate?: string;
  notes?: string;
  pdfUrl: string | null;
}

function formatCurrency(amount: number): string {
  return `$${amount.toFixed(2)}`;
}

function buildEmailHtml(data: SupplierEmailData): string {
  const itemRows = data.items
    .map(
      (item) => `
    <tr>
      <td style="padding: 10px 12px; border-bottom: 1px solid #eee;">${item.product_name}</td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-align: right;">${item.quantity_lbs.toFixed(2)} lbs</td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-align: right;">${formatCurrency(item.price_per_lb)}</td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #eee; text-align: right; font-weight: 600;">${formatCurrency(item.subtotal)}</td>
    </tr>`
    )
    .join('');

  const deliveryLine = data.deliveryDate
    ? `<p style="margin: 4px 0; color: #333;"><strong>Expected Delivery:</strong> ${data.deliveryDate}</p>`
    : '';

  const notesSection = data.notes
    ? `<div style="margin-top: 20px; padding: 12px 16px; background: #fffbeb; border-radius: 8px;">
        <p style="margin: 0; font-size: 13px; color: #92400e; font-weight: 600;">Notes</p>
        <p style="margin: 4px 0 0 0; color: #78350f;">${data.notes}</p>
       </div>`
    : '';

  const pdfLink = data.pdfUrl
    ? `<div style="margin-top: 24px; text-align: center;">
        <a href="${data.pdfUrl}" style="display: inline-block; background: #2563eb; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600;">
          View Purchase Order
        </a>
       </div>`
    : '';

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Purchase Order ${data.poNumber}</title></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;">
  <div style="background: white; border-radius: 12px; padding: 32px; box-shadow: 0 2px 8px rgba(0,0,0,0.08);">
    <h1 style="color: #2563eb; margin: 0 0 8px 0; font-size: 22px;">New Purchase Order</h1>
    <p style="color: #666; margin: 0 0 24px 0;">from ${data.businessName}</p>

    <div style="background: #f8f8f8; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
      <p style="margin: 0; color: #333;"><strong>PO #:</strong> ${data.poNumber}</p>
      <p style="margin: 4px 0; color: #333;"><strong>To:</strong> ${data.supplierName}</p>
      ${deliveryLine}
    </div>

    <h3 style="color: #333; border-bottom: 2px solid #2563eb; padding-bottom: 8px; font-size: 16px;">Order Items</h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <thead>
        <tr style="background: #f8f8f8;">
          <th style="padding: 10px 12px; text-align: left; font-size: 13px; color: #666;">Product</th>
          <th style="padding: 10px 12px; text-align: right; font-size: 13px; color: #666;">Quantity</th>
          <th style="padding: 10px 12px; text-align: right; font-size: 13px; color: #666;">Price/lb</th>
          <th style="padding: 10px 12px; text-align: right; font-size: 13px; color: #666;">Subtotal</th>
        </tr>
      </thead>
      <tbody>${itemRows}</tbody>
    </table>

    <div style="border-top: 2px solid #eee; padding-top: 12px; text-align: right;">
      <span style="font-size: 20px; font-weight: 700; color: #111827;">Total: ${formatCurrency(data.totalAmount)}</span>
    </div>

    ${notesSection}
    ${pdfLink}

    <p style="color: #999; font-size: 12px; margin-top: 32px; text-align: center;">
      This purchase order was generated by ${data.businessName}. Please confirm receipt.
    </p>
  </div>
</body>
</html>`;
}

export async function sendSupplierEmail(data: SupplierEmailData): Promise<boolean> {
  // Skip if no supplier email
  if (!data.supplierEmail) {
    console.error('No supplier email address configured, skipping email notification');
    return false;
  }

  const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');

  if (!RESEND_API_KEY) {
    console.error('RESEND_API_KEY not configured, skipping supplier email for PO', data.poNumber);
    return false;
  }

  const html = buildEmailHtml(data);

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: `${data.businessName} <orders@resend.dev>`,
      to: [data.supplierEmail],
      subject: `Purchase Order ${data.poNumber} from ${data.businessName}`,
      html,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    console.error('Resend API error:', JSON.stringify(errorData));
    return false;
  }

  return true;
}
