import { logger } from '@/lib/logger';
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dndteWVybnRraHJjZG5oYWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzQ2MDAsImV4cCI6MjA3NzE1MDYwMH0.rtBxVV_dLIvTI-6X_a7wAHakWW7OUWS-pLq8n-igbBI';

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL === 'undefined') {
  logger.error('[SUPABASE] Environment variables missing:', {
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
    allEnvVars: import.meta.env
  });
  throw new Error(
    'Missing Supabase URL. Please set VITE_SUPABASE_URL environment variable.\n' +
    'Check your .env file in the project root.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'undefined') {
  logger.error('[SUPABASE] Environment variables missing:', {
    VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
    VITE_SUPABASE_ANON_KEY: import.meta.env.VITE_SUPABASE_ANON_KEY
  });
  throw new Error(
    'Missing Supabase key. Please set VITE_SUPABASE_PUBLISHABLE_KEY environment variable.\n' +
    'Check your .env file in the project root.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});